### ISSUE TITLE
CPXBannerViewHandler.java line 3

### ISSUE THREAD

**Issue by efeint01** [MakeOpinionGmbH/cpx-research-SDK-Android#2]
Hi, I'm facing this issue, 

```
com.makeopinion.cpxresearchlib.views.CPXBannerViewHandler$install$2$1.onTouch
Fatal Exception: java.lang.IllegalArgumentException: x must be >= 0
       at android.graphics.Bitmap.checkXYSign(Bitmap.java:435)
       at android.graphics.Bitmap.checkPixelAccess(Bitmap.java:1991)
       at android.graphics.Bitmap.getPixel(Bitmap.java:1896)
       at com.makeopinion.cpxresearchlib.views.CPXBannerViewHandler$install$2$1.onTouch(CPXBannerViewHandler.java:3)
       at android.view.View.dispatchTouchEvent(View.java:14598)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3151)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2830)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3151)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2830)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3151)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2830)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3151)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2830)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3151)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2830)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3151)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2830)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:508)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1877)
       at android.app.Activity.dispatchTouchEvent(Activity.java:4241)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:2)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:466)
       at android.view.View.dispatchPointerEvent(View.java:14876)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6326)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6099)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5554)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5611)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5577)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5729)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5585)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5786)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5558)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5611)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5577)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5585)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5558)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8455)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8406)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8349)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8592)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:241)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:8163)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

**Comment by MrBugBears** [comment]
Hey, thank you for reporting the issue. We address that crash in the next update.

**Comment by MrBugBears** [comment]
Version 1.5.7 has just been released and addresses this issue.
